# Generated by Django 6.0.4 on 2026-05-15 16:38

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('image_path', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('deleted_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'dj_products',
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_gt_zero')],
            },
        ),
    ]
